# Generated by Django 5.2.4 on 2025-08-04 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('campos', models.JSONField()),
                ('schema_version', models.IntegerField(default=1)),
                ('is_ativo', models.BooleanField(default=True)),
                ('protegido', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_remocao', models.DateTimeField(blank=True, null=True)),
                ('usuario_remocao', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'db_table': 'formulario',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
