# Generated by Django 5.2.2 on 2025-08-05 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_remocao', models.DateTimeField(blank=True, null=True)),
                ('usuario_remocao', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='FormularioSchemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.IntegerField(default=1)),
                ('is_ativo', models.BooleanField(default=True)),
                ('protegido', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_remocao', models.DateTimeField(blank=True, null=True)),
                ('usuario_remocao', models.CharField(blank=True, max_length=150, null=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respostas', models.JSONField()),
                ('calculados', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='forms.formulario')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.formularioschemas')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_id', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('select', 'Seleção'), ('boolean', 'Booleano'), ('calculated', 'Calculado')], max_length=20)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('multilinha', models.BooleanField(default=False)),
                ('capitalizar', models.BooleanField(default=False)),
                ('formula', models.TextField(blank=True, default='')),
                ('condicional', models.TextField(blank=True, default='')),
                ('dependencias', models.JSONField(blank=True, default=list)),
                ('validacoes', models.JSONField(blank=True, default=list)),
                ('opcoes', models.JSONField(blank=True, default=list)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='forms.formularioschemas')),
            ],
            options={
                'unique_together': {('schema', 'campo_id')},
            },
        ),
    ]
