# Generated by Django 5.2.4 on 2025-08-05 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='campos',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='usuario_remocao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterModelTable(
            name='formulario',
            table=None,
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas', models.JSONField()),
                ('calculados', models.JSONField(blank=True, null=True)),
                ('schema_version', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('is_ativo', models.BooleanField(default=True)),
                ('data_remocao', models.DateTimeField(blank=True, null=True)),
                ('usuario_remocao', models.CharField(blank=True, max_length=150, null=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='forms.formulario')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_id', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('select', 'Seleção'), ('boolean', 'Booleano'), ('calculated', 'Calculado')], max_length=20)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('definicoes', models.JSONField(blank=True, default=dict)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='forms.formulario')),
            ],
            options={
                'unique_together': {('formulario', 'campo_id')},
            },
        ),
    ]
